"use strict";

/* Stage 10 - Live Job Discovery Engine.
   Profile-driven Adzuna search via Supabase Edge Function. No Adzuna secret is exposed client-side. */

const S10_PROFILE_KEY="irelandJobHuntOS_profileV1";
const S10_STATE_KEY="irelandJobHuntOS";
const s10q=id=>document.getElementById(id);
const s10esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const s10arr=value=>Array.isArray(value)?value:String(value||"").split(/[,\n]/).map(v=>v.trim()).filter(Boolean);
let s10Results=[];
let s10Client=null;

function s10Profile(){try{return JSON.parse(localStorage.getItem(S10_PROFILE_KEY)||"{}");}catch{return {};}}
function s10State(){try{return JSON.parse(localStorage.getItem(S10_STATE_KEY)||"{}");}catch{return {};}}
function s10SaveState(state){localStorage.setItem(S10_STATE_KEY,JSON.stringify(state));if(typeof refreshAll==="function")refreshAll();}
function s10Today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function s10Words(text){return [...new Set(String(text||"").toLowerCase().replace(/[^a-z0-9+#.\- ]/g," ").split(/\s+/).filter(w=>w.length>2))];}
function s10ProfileData(){const p=s10Profile();return {roles:s10arr(p.targetRoles||p.targetRole||p.roles).slice(0,8),skills:[...s10arr(p.professionalSkills),...s10arr(p.softSkills)].filter((v,i,a)=>a.findIndex(x=>x.toLowerCase()===v.toLowerCase())===i).slice(0,40),location:String(p.location||p.preferredLocation||"Ireland").trim()||"Ireland"};}
function s10SearchTerms(){const data=s10ProfileData();const roleTerms=data.roles.slice(0,4);const skillTerms=data.skills.slice(0,Math.max(0,5-roleTerms.length));return [...new Set([...roleTerms,...skillTerms].map(v=>v.trim()).filter(Boolean))].slice(0,5);}
function s10Salary(job){if(job.salary_min==null&&job.salary_max==null)return "Salary not listed";const fmt=n=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);if(job.salary_min!=null&&job.salary_max!=null)return `${fmt(job.salary_min)} – ${fmt(job.salary_max)}`;return job.salary_min!=null?`From ${fmt(job.salary_min)}`:`Up to ${fmt(job.salary_max)}`;}
function s10Date(value){if(!value)return "";const d=new Date(value);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short"}).format(d);}

function s10Score(job){const data=s10ProfileData();const hay=`${job.title||""} ${job.description||""} ${job.category||""}`.toLowerCase();const title=String(job.title||"").toLowerCase();const matchedSkills=data.skills.filter(skill=>hay.includes(skill.toLowerCase())).slice(0,12);let roleScore=0;let matchedRole="";for(const role of data.roles){const r=role.toLowerCase();if(title.includes(r)||r.includes(title)){roleScore=55;matchedRole=role;break;}const rw=s10Words(role);const tw=new Set(s10Words(title));const overlap=rw.filter(w=>tw.has(w)).length;if(rw.length&&overlap/rw.length>=.5&&overlap>0&&roleScore<40){roleScore=40;matchedRole=role;}}
  const skillScore=data.skills.length?Math.min(40,Math.round((matchedSkills.length/Math.min(10,data.skills.length))*40)):0;
  const queryBonus=job.matched_query&&hay.includes(String(job.matched_query).toLowerCase())?5:0;
  const score=Math.min(99,roleScore+skillScore+queryBonus);
  const reasons=[];if(matchedRole)reasons.push(`Title aligns with ${matchedRole}`);if(matchedSkills.length)reasons.push(`Matched skills: ${matchedSkills.slice(0,6).join(", ")}`);if(job.matched_query)reasons.push(`Found through: ${job.matched_query}`);
  return {score,matchedSkills,matchedRole,reasons};
}

function s10EnsureStyles(){if(s10q("stage10Styles"))return;const st=document.createElement("style");st.id="stage10Styles";st.textContent=`
.s10-shell{display:grid;gap:16px}.s10-controls{display:grid;grid-template-columns:2fr 1.2fr .8fr auto;gap:10px;align-items:end}.s10-profile{display:flex;gap:8px;flex-wrap:wrap}.s10-chip{font-size:11px;padding:6px 9px;border:1px solid var(--border);border-radius:999px;background:var(--surface2);color:var(--muted)}.s10-results{display:grid;gap:12px}.s10-card{padding:16px;border:1px solid var(--border);border-radius:13px;background:var(--surface)}.s10-head{display:flex;justify-content:space-between;gap:15px;align-items:start}.s10-head h3{margin:0 0 3px}.s10-company{color:var(--muted);font-size:12px}.s10-score{min-width:64px;text-align:center;padding:9px;border-radius:10px;border:1px solid rgba(40,209,124,.35);color:var(--accent);font-weight:800}.s10-meta{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:11px;margin:10px 0}.s10-desc{color:var(--muted);line-height:1.55;font-size:12px}.s10-match{margin-top:11px;padding:10px;border-radius:9px;background:var(--surface2);font-size:11px}.s10-match strong{color:var(--accent)}.s10-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.s10-actions a,.s10-actions button{border:1px solid var(--border);background:var(--surface2);color:var(--text);padding:8px 11px;border-radius:8px;text-decoration:none;cursor:pointer}.s10-actions .primary{background:var(--accent);border-color:var(--accent);color:#07130d;font-weight:700}.s10-status{padding:25px;text-align:center;color:var(--muted)}.s10-count{color:var(--muted);font-size:12px}@media(max-width:900px){.s10-controls{grid-template-columns:1fr 1fr}.s10-controls .s10-searchbtn{grid-column:1/-1}}@media(max-width:560px){.s10-controls{grid-template-columns:1fr}.s10-head{align-items:flex-start}.s10-actions>*{flex:1;text-align:center}}
`;document.head.appendChild(st);}

function s10CreatePage(){if(s10q("liveSearchPage"))return;const placeholder=s10q("placeholderPage")||document.querySelector("main");if(!placeholder)return;const page=document.createElement("section");page.className="page";page.id="liveSearchPage";page.innerHTML=`
<div class="page-heading"><div><div class="eyebrow">LIVE JOB DISCOVERY</div><h1>Jobs matched to your profile</h1><p>Search current Ireland vacancies using your target roles and skills, rank them locally, and save the strongest opportunities to Job Tracker.</p></div></div>
<div class="s10-shell"><section class="panel"><div class="analysis-card-head"><div><div class="eyebrow">SEARCH PROFILE</div><h3>What the engine will search</h3></div><span class="analysis-count">Adzuna live jobs</span></div><div id="s10ProfileChips" class="s10-profile"></div></section>
<section class="panel"><div class="s10-controls"><div class="field"><label for="s10Query">Job title or skill</label><input id="s10Query" placeholder="Leave blank to use your saved profile automatically"></div><div class="field"><label for="s10Location">Location</label><input id="s10Location" placeholder="Ireland"></div><div class="field"><label for="s10MinScore">Minimum match</label><select id="s10MinScore"><option value="0">Show all</option><option value="40">40%+</option><option value="60">60%+</option><option value="75">75%+</option></select></div><button class="btn s10-searchbtn" id="s10Search">Search live jobs</button></div></section>
<div class="job-count-row"><span id="s10Count" class="s10-count">Ready to search</span><button class="link-button" id="s10ProfileSearch">Use saved profile</button></div><section id="s10Results" class="s10-results"><div class="panel s10-status">Your live job results will appear here.</div></section></div>`;placeholder.parentNode.insertBefore(page,placeholder);}

function s10ShowPage(){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page==="search"));s10q("liveSearchPage")?.classList.add("active");if(s10q("pageTitle"))s10q("pageTitle").textContent="Job Search";s10q("sidebar")?.classList.remove("open");s10RenderProfile();window.scrollTo({top:0,behavior:"smooth"});}
function s10RenderProfile(){const d=s10ProfileData();const terms=s10SearchTerms();const host=s10q("s10ProfileChips");if(host)host.innerHTML=(terms.length?terms:["Add target roles or skills in Profile"]).map(v=>`<span class="s10-chip">${s10esc(v)}</span>`).join("");if(s10q("s10Location")&&!s10q("s10Location").value)s10q("s10Location").value=d.location;}

async function s10ResolveClient(){if(s10Client)return s10Client;for(let i=0;i<80;i++){const c=window.JobHuntCloudCV?.getClient?.();if(c){s10Client=c;return c;}await new Promise(r=>setTimeout(r,100));}return null;}
async function s10Search(useProfile=true){const host=s10q("s10Results");const button=s10q("s10Search");const manual=String(s10q("s10Query")?.value||"").trim();const searches=manual?[manual]:s10SearchTerms();if(!searches.length){host.innerHTML='<div class="panel s10-status">Add at least one target role or professional skill in your Profile, or enter a manual search term.</div>';return;}const client=await s10ResolveClient();if(!client){host.innerHTML='<div class="panel s10-status">The cloud job-search service could not load. Refresh the page and try again.</div>';return;}button.disabled=true;button.textContent="Searching…";host.innerHTML='<div class="panel s10-status">Searching current Ireland vacancies…</div>';try{const {data,error}=await client.functions.invoke("search-jobs",{body:{searches,location:String(s10q("s10Location")?.value||"Ireland").trim()||"Ireland",resultsPerPage:12}});if(error)throw error;if(data?.error)throw new Error(data.error);s10Results=(Array.isArray(data?.results)?data.results:[]).map(job=>({...job,_match:s10Score(job)})).sort((a,b)=>b._match.score-a._match.score);s10RenderResults();}catch(error){console.error("Stage 10 search failed",error);host.innerHTML=`<div class="panel s10-status">Live search failed. ${s10esc(error?.message||"Please try again.")}</div>`;}finally{button.disabled=false;button.textContent="Search live jobs";}}
function s10RenderResults(){const host=s10q("s10Results");const min=Number(s10q("s10MinScore")?.value||0);const list=s10Results.filter(j=>j._match.score>=min);if(s10q("s10Count"))s10q("s10Count").textContent=`${list.length} live ${list.length===1?"job":"jobs"}`;if(!list.length){host.innerHTML='<div class="panel s10-status">No jobs match this filter. Try lowering the match threshold or using a broader title/skill.</div>';return;}host.innerHTML=list.map(s10Card).join("");host.querySelectorAll("[data-s10-save]").forEach(btn=>btn.addEventListener("click",()=>s10SaveJob(btn.dataset.s10Save,btn)));}
function s10Card(job){const m=job._match;const desc=String(job.description||"");return `<article class="s10-card"><div class="s10-head"><div><h3>${s10esc(job.title||"Untitled role")}</h3><div class="s10-company">${s10esc(job.company||"Company not listed")}</div></div><div class="s10-score">${m.score}%</div></div><div class="s10-meta"><span>📍 ${s10esc(job.location||"Ireland")}</span><span>${s10esc(s10Salary(job))}</span>${job.contract_time?`<span>${s10esc(job.contract_time)}</span>`:""}${job.created?`<span>Posted ${s10esc(s10Date(job.created))}</span>`:""}</div><div class="s10-desc">${s10esc(desc.length>420?`${desc.slice(0,420)}…`:desc)}</div><div class="s10-match"><strong>Why it matches:</strong> ${s10esc(m.reasons.length?m.reasons.join(" · "):"No strong profile evidence found yet; review the description manually.")}</div><div class="s10-actions">${job.redirect_url?`<a class="primary" href="${s10esc(job.redirect_url)}" target="_blank" rel="noopener noreferrer">View job ↗</a>`:""}<button data-s10-save="${s10esc(job.id)}">Save to Tracker</button></div></article>`;}

function s10SaveJob(id,button){const job=s10Results.find(j=>String(j.id)===String(id));if(!job)return;const state=s10State();state.jobs=Array.isArray(state.jobs)?state.jobs:[];const duplicate=state.jobs.some(j=>(job.redirect_url&&j.jobUrl===job.redirect_url)||(job.id&&j.sourceJobId===job.id));if(duplicate){button.textContent="Already saved";button.disabled=true;return;}const newJob={id:`job_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,company:job.company||"",position:job.title||"",jobUrl:job.redirect_url||"",location:job.location||"",workArrangement:"",salary:s10Salary(job)==="Salary not listed"?"":s10Salary(job),jobType:job.contract_time||job.contract_type||"",dateDiscovered:s10Today(),applicationDeadline:"",dateApplied:"",status:"Saved",matchScore:job._match.score,followUpDate:"",requiredSkills:job._match.matchedSkills||[],notes:`Discovered through Adzuna live search. Search term: ${job.matched_query||"profile match"}.`,source:"Adzuna",sourceJobId:job.id||"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.jobs.unshift(newJob);state.activity=Array.isArray(state.activity)?state.activity:[];state.activity.unshift({id:`act_${Date.now()}`,text:`Saved live job ${newJob.position} at ${newJob.company}`,time:new Date().toISOString()});s10SaveState(state);button.textContent="Saved ✓";button.disabled=true;}

function s10Bind(){const nav=document.querySelector('.nav [data-page="search"]');nav?.addEventListener("click",()=>setTimeout(s10ShowPage,0));s10q("s10Search")?.addEventListener("click",()=>s10Search(false));s10q("s10ProfileSearch")?.addEventListener("click",()=>{if(s10q("s10Query"))s10q("s10Query").value="";s10RenderProfile();s10Search(true);});s10q("s10MinScore")?.addEventListener("change",s10RenderResults);s10q("s10Query")?.addEventListener("keydown",e=>{if(e.key==="Enter")s10Search(false);});}
function s10Init(){s10EnsureStyles();s10CreatePage();s10RenderProfile();s10Bind();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",s10Init);else s10Init();
