"use strict";

/* Stage 8 - Follow-up & Application Communication System.
   Browser-only, user-controlled, and additive to existing tracker data. */

const S8_KEY="irelandJobHuntOS";
const S8_ACTIVE_STATUSES=new Set(["Applied","Assessment","Interview","Final Interview"]);
const s8q=id=>document.getElementById(id);
const s8esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));

function s8State(){try{return JSON.parse(localStorage.getItem(S8_KEY)||"{}");}catch{return {};}}
function s8Save(state){localStorage.setItem(S8_KEY,JSON.stringify(state));if(typeof refreshAll==="function")refreshAll();}
function s8Today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function s8Date(value){if(!value)return null;const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?null:d;}
function s8Fmt(value){const d=s8Date(value);return d?new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric"}).format(d):"Not scheduled";}
function s8AddDays(value,days){const d=s8Date(value)||new Date();d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function s8DaysFromToday(value){const d=s8Date(value);if(!d)return null;const t=s8Date(s8Today());return Math.round((d-t)/86400000);}
function s8Status(job){if(!job.followUpDate)return "unscheduled";const days=s8DaysFromToday(job.followUpDate);if(days<0)return "overdue";if(days===0)return "today";if(days<=7)return "upcoming";return "later";}
function s8Recommended(job){const base=job.dateApplied||job.updatedAt?.slice(0,10)||job.dateDiscovered||s8Today();if(job.status==="Interview"||job.status==="Final Interview")return s8AddDays(base,1);return s8AddDays(base,5);}
function s8Jobs(){const state=s8State();return Array.isArray(state.jobs)?state.jobs:[];}
function s8ActiveJobs(){return s8Jobs().filter(job=>S8_ACTIVE_STATUSES.has(job.status));}

function s8Template(job,type){
  const role=job.position||"the role";const company=job.company||"your organisation";
  const templates={
    application:{subject:`Follow-up on ${role} application`,body:`Hello,\n\nI hope you are well. I am following up regarding my application for the ${role} position at ${company}. I remain very interested in the opportunity and would be grateful for any update you can share on the hiring process or next steps.\n\nPlease let me know if I can provide any additional information.\n\nKind regards,`},
    assessment:{subject:`Follow-up on ${role} assessment`,body:`Hello,\n\nI am following up regarding the assessment stage for the ${role} position at ${company}. I remain very interested in the opportunity and wanted to check whether there are any updates on the next stage of the process.\n\nPlease let me know if you need anything further from me.\n\nKind regards,`},
    interview:{subject:`Thank you — ${role} interview`,body:`Hello,\n\nThank you for taking the time to speak with me about the ${role} position at ${company}. I appreciated the opportunity to learn more about the role and the team. Our conversation strengthened my interest in the position, and I would be happy to provide any additional information that may be useful.\n\nThank you again for your time and consideration.\n\nKind regards,`},
    interviewfollow:{subject:`Follow-up after ${role} interview`,body:`Hello,\n\nI hope you are well. I am following up after my interview for the ${role} position at ${company}. I remain very interested in the opportunity and would appreciate any update you can share regarding the next steps or expected timeline.\n\nThank you again for your time and consideration.\n\nKind regards,`},
    keepintouch:{subject:`Staying in touch — ${role}`,body:`Hello,\n\nThank you again for considering me for the ${role} position at ${company}. I appreciated the opportunity to learn more about the organisation. I would be glad to stay in touch and be considered for suitable opportunities in the future.\n\nKind regards,`}
  };
  return templates[type]||templates.application;
}

function s8DefaultTemplate(job){if(job.status==="Assessment")return "assessment";if(job.status==="Interview"||job.status==="Final Interview")return "interviewfollow";return "application";}

function s8EnsureStyles(){if(s8q("stage8Styles"))return;const st=document.createElement("style");st.id="stage8Styles";st.textContent=`
.s8-shell{display:grid;gap:16px}.s8-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.s8-stat{padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.s8-stat span{display:block;color:var(--muted);font-size:11px}.s8-stat strong{display:block;font-size:26px;margin-top:5px}.s8-toolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.s8-toolbar button{border:1px solid var(--border);background:var(--surface2);color:var(--text);padding:8px 11px;border-radius:9px;cursor:pointer}.s8-toolbar button.active{border-color:var(--accent);color:var(--accent)}.s8-list{display:grid;gap:12px}.s8-card{border:1px solid var(--border);border-radius:12px;background:var(--surface);padding:15px}.s8-head{display:flex;justify-content:space-between;gap:14px;align-items:start}.s8-head h3{margin:0}.s8-head small{color:var(--muted)}.s8-badge{font-size:10px;padding:5px 8px;border-radius:999px;border:1px solid var(--border)}.s8-badge.overdue{color:#ff8d8d;border-color:rgba(255,141,141,.35)}.s8-badge.today{color:var(--warn);border-color:rgba(245,186,69,.35)}.s8-badge.upcoming{color:var(--accent);border-color:rgba(40,209,124,.35)}.s8-meta{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:11px;margin-top:9px}.s8-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.s8-actions button{padding:7px 10px;border-radius:8px;border:1px solid var(--border);background:var(--surface2);color:var(--text);cursor:pointer}.s8-actions .primary{background:var(--accent);color:#06120c;border-color:var(--accent);font-weight:700}.s8-empty{padding:28px;text-align:center;color:var(--muted)}.s8-composer{display:grid;gap:12px}.s8-composer textarea{min-height:230px;resize:vertical}.s8-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.s8-history{display:grid;gap:7px;margin-top:9px}.s8-history div{font-size:11px;color:var(--muted);padding:7px 9px;background:var(--surface2);border-radius:8px}.s8-modal{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.62);display:grid;place-items:center;padding:20px}.s8-modal[hidden]{display:none}.s8-dialog{width:min(760px,100%);max-height:90vh;overflow:auto;background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:18px}.s8-dialog-head{display:flex;justify-content:space-between;gap:12px}.s8-dialog-head button{border:0;background:transparent;color:var(--text);font-size:24px;cursor:pointer}@media(max-width:850px){.s8-summary{grid-template-columns:1fr 1fr}.s8-grid{grid-template-columns:1fr}}@media(max-width:520px){.s8-summary{grid-template-columns:1fr}.s8-actions button{flex:1}}
`;document.head.appendChild(st);}

function s8CreatePage(){if(s8q("followUpPage"))return;const placeholder=s8q("placeholderPage")||document.querySelector("main");if(!placeholder)return;const page=document.createElement("section");page.className="page";page.id="followUpPage";page.innerHTML=`
<div class="page-heading"><div><div class="eyebrow">APPLICATION FOLLOW-UP</div><h1>Follow-up & Communication</h1><p>See what needs attention, prepare professional messages, and record every follow-up without sending anything automatically.</p></div></div>
<div class="s8-shell"><section class="s8-summary" id="s8Summary"></section><section class="panel"><div class="s8-toolbar" id="s8Filters"><button data-s8-filter="due" class="active">Due now</button><button data-s8-filter="today">Today</button><button data-s8-filter="upcoming">Next 7 days</button><button data-s8-filter="unscheduled">Unscheduled</button><button data-s8-filter="all">All active</button></div></section><section id="s8List" class="s8-list"></section></div>`;placeholder.parentNode.insertBefore(page,placeholder);}

function s8AddNav(){const nav=document.querySelector(".nav");if(!nav||nav.querySelector('[data-page="followups"]'))return;const btn=document.createElement("button");btn.dataset.page="followups";btn.innerHTML='✉ Follow-ups <span id="s8NavCount" style="margin-left:auto"></span>';const daily=nav.querySelector('[data-page="daily"]');nav.insertBefore(btn,daily||null);btn.addEventListener("click",s8ShowPage);}
function s8ShowPage(){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page==="followups"));s8q("followUpPage")?.classList.add("active");if(s8q("pageTitle"))s8q("pageTitle").textContent="Follow-up & Communication";s8q("sidebar")?.classList.remove("open");s8Render();window.scrollTo({top:0,behavior:"smooth"});}

let s8Filter="due";
function s8Filtered(){return s8ActiveJobs().filter(job=>{const st=s8Status(job);if(s8Filter==="all")return true;if(s8Filter==="due")return st==="overdue"||st==="today";return st===s8Filter;}).sort((a,b)=>(a.followUpDate||"9999-12-31").localeCompare(b.followUpDate||"9999-12-31"));}
function s8Summary(){const jobs=s8ActiveJobs();const due=jobs.filter(j=>["overdue","today"].includes(s8Status(j))).length;const today=jobs.filter(j=>s8Status(j)==="today").length;const upcoming=jobs.filter(j=>s8Status(j)==="upcoming").length;const unscheduled=jobs.filter(j=>s8Status(j)==="unscheduled").length;return {due,today,upcoming,unscheduled};}

function s8Render(){const summary=s8Summary();const host=s8q("s8Summary");if(host)host.innerHTML=[[summary.due,"Due now"],[summary.today,"Due today"],[summary.upcoming,"Next 7 days"],[summary.unscheduled,"Need scheduling"]].map(([n,l])=>`<article class="s8-stat"><span>${l}</span><strong>${n}</strong></article>`).join("");const nav=s8q("s8NavCount");if(nav)nav.textContent=summary.due?String(summary.due):"";const list=s8q("s8List");if(!list)return;const jobs=s8Filtered();if(!jobs.length){list.innerHTML='<section class="panel s8-empty">Nothing needs attention in this view.</section>';return;}list.innerHTML=jobs.map(s8Card).join("");list.querySelectorAll("[data-s8-compose]").forEach(b=>b.addEventListener("click",()=>s8OpenComposer(b.dataset.s8Compose)));list.querySelectorAll("[data-s8-done]").forEach(b=>b.addEventListener("click",()=>s8Record(b.dataset.s8Done)));list.querySelectorAll("[data-s8-snooze]").forEach(b=>b.addEventListener("click",()=>s8Snooze(b.dataset.s8Snooze,Number(b.dataset.days||5))));list.querySelectorAll("[data-s8-schedule]").forEach(b=>b.addEventListener("click",()=>s8Schedule(b.dataset.s8Schedule)));}

function s8Card(job){const st=s8Status(job);const label={overdue:"Overdue",today:"Due today",upcoming:"Upcoming",later:"Scheduled",unscheduled:"Unscheduled"}[st];const hist=Array.isArray(job.followUpHistory)?job.followUpHistory:[];return `<article class="s8-card"><div class="s8-head"><div><h3>${s8esc(job.position)}</h3><small>${s8esc(job.company)} · ${s8esc(job.status)}</small></div><span class="s8-badge ${st}">${label}</span></div><div class="s8-meta"><span>Follow-up: <strong>${s8Fmt(job.followUpDate)}</strong></span>${job.lastFollowUpDate?`<span>Last contacted: <strong>${s8Fmt(job.lastFollowUpDate)}</strong></span>`:""}<span>History: <strong>${hist.length}</strong></span></div><div class="s8-actions"><button class="primary" data-s8-compose="${s8esc(job.id)}">Prepare message</button><button data-s8-done="${s8esc(job.id)}">Mark followed up</button>${st==="unscheduled"?`<button data-s8-schedule="${s8esc(job.id)}">Schedule suggested date</button>`:`<button data-s8-snooze="${s8esc(job.id)}" data-days="5">Snooze 5 days</button>`}</div>${hist.length?`<div class="s8-history">${hist.slice(-3).reverse().map(h=>`<div>${s8esc(s8Fmt(h.date))} · ${s8esc(h.type||"Follow-up")}</div>`).join("")}</div>`:""}</article>`;}

function s8UpdateJob(id,mutator,activity){const state=s8State();state.jobs=Array.isArray(state.jobs)?state.jobs:[];const idx=state.jobs.findIndex(j=>String(j.id)===String(id));if(idx<0)return;mutator(state.jobs[idx]);state.jobs[idx].updatedAt=new Date().toISOString();state.activity=Array.isArray(state.activity)?state.activity:[];if(activity)state.activity.unshift({id:`act_${Date.now()}`,text:activity,time:new Date().toISOString()});s8Save(state);s8Render();}
function s8Record(id,type="Follow-up sent"){const job=s8Jobs().find(j=>String(j.id)===String(id));if(!job)return;s8UpdateJob(id,j=>{j.followUpHistory=Array.isArray(j.followUpHistory)?j.followUpHistory:[];j.followUpHistory.push({date:s8Today(),type});j.lastFollowUpDate=s8Today();j.followUpDate=s8AddDays(s8Today(),5);},`Followed up on ${job.position} at ${job.company}`);}
function s8Snooze(id,days){s8UpdateJob(id,j=>{j.followUpDate=s8AddDays(s8Today(),days);},null);}
function s8Schedule(id){const job=s8Jobs().find(j=>String(j.id)===String(id));if(!job)return;s8UpdateJob(id,j=>{j.followUpDate=s8Recommended(j);},`Scheduled follow-up for ${job.position} at ${job.company}`);}

function s8EnsureModal(){if(s8q("s8Modal"))return;const modal=document.createElement("div");modal.id="s8Modal";modal.className="s8-modal";modal.hidden=true;modal.innerHTML=`<div class="s8-dialog"><div class="s8-dialog-head"><div><div class="eyebrow">MESSAGE PREP</div><h3 id="s8ComposerTitle">Follow-up message</h3></div><button id="s8Close" aria-label="Close">×</button></div><div class="s8-composer"><div class="s8-grid"><div class="field"><label>Template</label><select id="s8Template"><option value="application">Application follow-up</option><option value="assessment">Assessment follow-up</option><option value="interview">Post-interview thank you</option><option value="interviewfollow">Interview follow-up</option><option value="keepintouch">Keep in touch</option></select></div><div class="field"><label>Subject</label><input id="s8Subject"></div></div><div class="field"><label>Message</label><textarea id="s8Body"></textarea></div><div class="s8-actions"><button class="primary" id="s8Copy">Copy message</button><button id="s8CopySubject">Copy subject</button><button id="s8MarkFromComposer">Mark followed up</button></div><p class="s8-meta">Messages are templates only. Review the wording and recipient before sending from your own email account.</p></div></div>`;document.body.appendChild(modal);s8q("s8Close").addEventListener("click",s8CloseComposer);modal.addEventListener("click",e=>{if(e.target===modal)s8CloseComposer();});s8q("s8Template").addEventListener("change",s8RefreshComposer);s8q("s8Copy").addEventListener("click",()=>s8Copy(s8q("s8Body").value,"Message copied"));s8q("s8CopySubject").addEventListener("click",()=>s8Copy(s8q("s8Subject").value,"Subject copied"));s8q("s8MarkFromComposer").addEventListener("click",()=>{if(window.__s8JobId){s8Record(window.__s8JobId,"Follow-up message prepared");s8CloseComposer();}});}
function s8OpenComposer(id){const job=s8Jobs().find(j=>String(j.id)===String(id));if(!job)return;s8EnsureModal();window.__s8JobId=String(id);s8q("s8ComposerTitle").textContent=`${job.position} — ${job.company}`;s8q("s8Template").value=s8DefaultTemplate(job);s8RefreshComposer();s8q("s8Modal").hidden=false;document.body.style.overflow="hidden";}
function s8RefreshComposer(){const job=s8Jobs().find(j=>String(j.id)===String(window.__s8JobId));if(!job)return;const t=s8Template(job,s8q("s8Template").value);s8q("s8Subject").value=t.subject;s8q("s8Body").value=t.body;}
function s8CloseComposer(){if(s8q("s8Modal"))s8q("s8Modal").hidden=true;document.body.style.overflow="";}
async function s8Copy(text,label){try{await navigator.clipboard.writeText(text);const btn=document.activeElement;const old=btn?.textContent;if(btn){btn.textContent=label;setTimeout(()=>btn.textContent=old,1200);}}catch{alert("Copy failed. Please copy the text manually.");}}

function s8Init(){s8EnsureStyles();s8CreatePage();s8AddNav();s8EnsureModal();const filters=s8q("s8Filters");filters?.addEventListener("click",e=>{const btn=e.target.closest("[data-s8-filter]");if(!btn)return;s8Filter=btn.dataset.s8Filter;filters.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b===btn));s8Render();});s8Render();document.addEventListener("click",e=>{if(e.target.closest('[data-page="jobs"], [data-page="dashboard"]'))setTimeout(s8Render,100);});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",s8Init);else s8Init();
